version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: marketplace-backend
    container_name: marketplace-backend
    restart: unless-stopped
    privileged: true
    volumes:
      - backend_data:/data:rw
    ports: 
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - marketplace_net
    environment:
      NAME: "The Marketplace"

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    expose:
      - "6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    expose:
      - "8081"

  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    expose:
      - "7474"
      - "7687"
    volumes:
      - neo4j_data:/data

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert:/etc/nginx/cert:ro # Replace with actual path to SSL certificate and key
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    networks:
      - marketplace_net


networks:
  marketplace_net:
    name: marketplace_net

volumes:
  redis_data:
    name: redis_data
  neo4j_data:
    name: neo4j_data
  backend_data:
    name: backend_data