apiVersion: v1
kind: Namespace
metadata:
  name: marketplace

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: marketplace
type: Opaque
data:
  POSTGRES_USER: <base64-encoded-username>
  POSTGRES_PASSWORD: <base64-encoded-password>

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: marketplace
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: <database-name>

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: marketplace
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres:13.1
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: marketplace
spec:
  selector:
    app: pgadmin
  ports:
  - name: pgadmin
    protocol: TCP
    port: 80
    targetPort: 5050
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: <pgadmin-email>
            - name: PGADMIN_DEFAULT_PASSWORD
              value: <pgadmin-password>
          ports:
            - containerPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: marketplace
        image: golang:1.19
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: marketplace
spec:
  selector:
    app: golang
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: marketplace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: app-backendconfig
spec:
  timeoutSec: 300
  connectionDraining:
    drainingTimeoutSec: 300
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_PASSWORD: <base64-encoded-database-password>