name: Build and Push Docker Image


on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: 'read'

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  APP_NAME: "marketplace"
  TAG: "v0.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -o ${{ env.APP_NAME }} cmd/backend/main.go

    - name: Create Tag
      id: create_tag
      uses: mathieudutour/github-tag-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        tag_message: 'Release ${{ github.ref }}'
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this release:
          - Add feature A
          - Fix issue B
        draft: false
        prerelease: false
