name: Create Release


on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: 'read'

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  APP_NAME: "marketplace"
  TAG: "v0.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -o ${{ env.APP_NAME }} cmd/backend/main.go

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_VVIP }}
      with:
        tag_name: v1.0.5
        release_name: Release v1.0.0
        body: |
          This is the release body.
          It can contain multiple lines of text.
        draft: false
        prerelease: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APP_NAME }} 
        path: ${{ env.APP_NAME }} 

